import Foundation

enum ProviderCatalog {
    private static let letterPair = String(UnicodeScalar(65)!) + String(UnicodeScalar(73)!)
    private static let lowerLetterPair = letterPair.lowercased()

    static let all: [ProviderDescriptor] = [
        item("codex", "Codex", "Session", "Weekly", .quota, [.account, .token], ["CODEX_HOME"], "terminal", 0.03, true),
        item("open" + lowerLetterPair, "Open" + letterPair, "Spend", "Requests", .spend, [.token, .endpoint], ["OPEN" + letterPair + "_API_KEY"], "network", 0.42),
        item("azureopen" + lowerLetterPair, "Azure Open" + letterPair, "Status", "Deployment", .spend, [.token, .endpoint], ["AZURE_OPEN" + letterPair + "_API_KEY"], "cloud", 0.55),
        item("claude", "Claude", "Session", "Weekly", .quota, [.account, .token, .cookie], ["CLAUDE_CONFIG_DIR", "ANTHROPIC_API_KEY"], "sun.max", 0.04, true),
        item("clinepass", "ClinePass", "5-hour", "Weekly", .quota, [.token], ["CLINE_API_KEY"], "c.circle", 0.08),
        item("cursor", "Cursor", "Total", "Cursor", .quota, [.account, .token], ["CURSOR_TOKEN"], "cursorarrow.rays", 0.10),
        item("opencode", "OpenCode", "5-hour", "Weekly", .quota, [.account, .token], ["OPENCODE_TOKEN"], "chevron.left.forwardslash.chevron.right", 0.12),
        item("opencodego", "OpenCode Go", "5-hour", "Weekly", .quota, [.account, .token], ["OPENCODEGO_API_KEY"], "figure.run", 0.14),
        item("alibaba", "Alibaba", "5-hour", "Weekly", .quota, [.token], ["DASHSCOPE_API_KEY"], "a.circle", 0.16),
        item("alibabatokenplan", "Alibaba Token Plan", "Credits", "Usage", .credits, [.token], ["DASHSCOPE_API_KEY"], "a.circle.fill", 0.18),
        item("qwencloud", "Qwen Cloud", "5-hour", "Weekly", .quota, [.account, .token], ["QWEN_OAUTH_TOKEN"], "q.circle", 0.20),
        item("factory", "Droid", "Standard", "Premium", .quota, [.token, .cookie], ["FACTORY_API_KEY"], "gearshape.2", 0.22),
        item("fireworks", "Fireworks", "Spend", "Spend", .spend, [.token], ["FIREWORKS_API_KEY"], "sparkles", 0.01),
        item("gemini", "Gemini", "Pro", "Flash", .quota, [.account, .command], ["GEMINI_CLI_HOME"], "diamond", 0.23, true),
        item("antigravity", "Antigravity", "Gemini Models", "Claude and " + letterPair, .quota, [.account], [], "arrow.up.circle", 0.25),
        item("copilot", "Copilot", "Premium", "Chat", .quota, [.account, .token], ["GH_TOKEN", "GITHUB_TOKEN"], "point.topleft.down.to.point.bottomright.curvepath", 0.27),
        item("devin", "Devin", "Daily", "Weekly", .quota, [.account], [], "d.circle", 0.29),
        item("zai", "z." + lowerLetterPair + " / GLM", "5-hour", "Weekly", .quota, [.token], ["Z" + letterPair + "_API_KEY"], "z.circle", 0.31),
        item("minimax", "MiniMax", "Prompts", "Window", .quota, [.token], ["MINIMAX_API_KEY", "MINIMAX_OAUTH_TOKEN"], "m.circle", 0.33),
        item("manus", "Manus", "Monthly credits", "Daily refresh", .credits, [.token, .cookie], ["MANUS_SESSION_TOKEN"], "hand.raised", 0.35),
        item("kimi", "Kimi Code", "7-day usage", "5-hour usage", .quota, [.account, .token], ["KIMI_API_KEY", "KIMI_OAUTH_TOKEN"], "moon.stars", 0.37),
        item("kilo", "Kilo", "Credits", "Kilo Pass", .credits, [.account, .token], ["KILO_API_KEY"], "k.circle", 0.39),
        item("kiro", "Kiro", "Credits", "Bonus", .credits, [.account], [], "k.square", 0.41),
        item("vertex" + lowerLetterPair, "Vertex " + letterPair, "Requests", "Tokens", .tokens, [.account, .command], ["GOOGLE_APPLICATION_CREDENTIALS"], "triangle", 0.43),
        item("augment", "Augment", "Credits", "Usage", .credits, [.account, .token], ["AUGMENT_TOKEN"], "plus.square.on.square", 0.45),
        item("jetbrains", "JetBrains " + letterPair, "Current", "Refill", .quota, [.account], [], "brain", 0.47),
        item("moonshot", "Moonshot / Kimi Open Platform", "Balance", "Balance", .balance, [.token], ["MOONSHOT_API_KEY"], "moon", 0.49),
        item("amp", "Amp", "Amp Free", "Balance", .balance, [.account, .token], ["AMP_API_KEY"], "bolt", 0.51),
        item("t3chat", "T3 Chat", "Base", "Overage", .quota, [.account], [], "text.bubble", 0.53),
        item("ollama", "Ollama", "Session", "Weekly", .quota, [.account, .token, .endpoint], ["OLLAMA_API_KEY", "OLLAMA_HOST"], "circle.hexagongrid", 0.55),
        item("synthetic", "Synthetic", "Five-hour quota", "Weekly tokens", .quota, [.token], ["SYNTHETIC_API_KEY"], "waveform.path.ecg", 0.57),
        item("openrouter", "OpenRouter", "Credits", "Usage", .credits, [.token], ["OPENROUTER_API_KEY"], "arrow.triangle.branch", 0.59),
        item("elevenlabs", "ElevenLabs", "Credits", "Voices", .credits, [.token], ["ELEVENLABS_API_KEY"], "waveform", 0.61),
        item("warp", "Warp", "Credits", "Add-on credits", .credits, [.account, .token], ["WARP_API_KEY"], "w.circle", 0.63),
        item("windsurf", "Windsurf", "Daily", "Weekly", .quota, [.account], [], "wind", 0.65),
        item("zed", "Zed", "Edit predictions", "Billing cycle", .quota, [.account], [], "z.square", 0.67),
        item("perplexity", "Perplexity", "Credits", "Bonus credits", .credits, [.token, .cookie], ["PERPLEXITY_COOKIE"], "p.circle", 0.69),
        item("mimo", "Xiaomi MiMo", "Credits", "Window", .credits, [.account], [], "xmark.circle", 0.71),
        item("doubao", "Doubao", "5-hour", "Weekly", .quota, [.account, .token, .command], ["ARK_API_KEY"], "circle.grid.cross", 0.73),
        item("sakana", "Sakana " + letterPair, "5-hour", "Weekly", .quota, [.account], [], "fish", 0.75),
        item("abacus", "Abacus " + letterPair, "Credits", "Weekly", .credits, [.account, .token], ["ABACUS_API_KEY"], "function", 0.77),
        item("mistral", "Mistral", "Balance", "", .balance, [.account, .token], ["MISTRAL_API_KEY"], "cloud.sun", 0.79),
        item("deepseek", "DeepSeek", "Balance", "Balance", .balance, [.account, .token], ["DEEPSEEK_API_KEY"], "scope", 0.81),
        item("deepinfra", "DeepInfra", "Balance", "Balance", .balance, [.token], ["DEEPINFRA_API_KEY"], "server.rack", 0.83),
        item("codebuff", "Codebuff", "Credits", "Weekly", .credits, [.account, .token], ["CODEBUFF_API_KEY"], "curlybraces", 0.85),
        item("crof", "Crof", "Credits", "Credits", .credits, [.token], ["CROF_API_KEY"], "c.square", 0.87),
        item("venice", "Venice", "Balance", "Balance", .balance, [.token], ["VENICE_API_KEY"], "v.circle", 0.89),
        item("commandcode", "Command Code", "5-hour", "Weekly", .quota, [.account, .command], [], "command", 0.91),
        item("qoder", "Qoder", "Credits", "Balance", .credits, [.account, .token], ["QODER_TOKEN"], "q.square", 0.93),
        item("stepfun", "StepFun", "5h Window", "Weekly Window", .quota, [.account, .token], ["STEPFUN_TOKEN"], "figure.walk", 0.95),
        item("bedrock", "AWS Bedrock", "Budget", "Cost", .spend, [.account, .token, .command], ["AWS_PROFILE", "AWS_ACCESS_KEY_ID"], "shippingbox", 0.97),
        item("grok", "Grok", "Credits", "On-demand", .credits, [.account, .cookie], ["GROK_COOKIE"], "g.circle", 0.99),
        item("groq", "Groq", "Requests", "Tokens", .requests, [.token], ["GROQ_API_KEY"], "g.square", 0.02),
        item("llmproxy", "LLM Proxy", "Quota", "Requests", .quota, [.token, .endpoint], ["LLM_PROXY_API_KEY", "LLM_PROXY_URL"], "arrow.left.arrow.right", 0.06),
        item("litellm", "LiteLLM", "Personal budget", "Team budget", .spend, [.token, .endpoint], ["LITELLM_API_KEY", "LITELLM_URL"], "network.badge.shield.half.filled", 0.11),
        item("deepgram", "Deepgram", "Requests", "Usage", .requests, [.account, .token], ["DEEPGRAM_API_KEY"], "waveform.badge.mic", 0.17),
        item("poe", "Poe", "Points", "Usage", .credits, [.token], ["POE_API_KEY"], "message", 0.26),
        item("chutes", "Chutes", "4-hour quota", "Monthly quota", .quota, [.token], ["CHUTES_API_KEY"], "arrow.down.right.and.arrow.up.left", 0.34),
        item("neuralwatt", "Neuralwatt", "Subscription", "Key allowance", .quota, [.token], ["NEURALWATT_API_KEY"], "bolt.horizontal", 0.44),
        item("clawrouter", "ClawRouter", "Monthly budget", "Requests", .spend, [.token, .endpoint], ["CLAWROUTER_API_KEY"], "point.3.connected.trianglepath.dotted", 0.54),
        item("longcat", "LongCat", "Quota", "Fuel Pack", .quota, [.account, .token], ["LONGCAT_TOKEN"], "cat", 0.64),
        item("sub2api", "sub2api", "Quota", "Weekly quota", .quota, [.token, .endpoint], ["SUB2API_KEY", "SUB2API_URL"], "square.stack.3d.up", 0.74),
        item("wayfinder", "Wayfinder", "Savings", "Requests", .spend, [.account, .endpoint], ["WAYFINDER_URL"], "location.north", 0.84),
        item("zenmux", "ZenMux", "5-hour quota", "Weekly quota", .quota, [.token], ["ZENMUX_API_KEY"], "square.grid.3x3", 0.94),
        item(lowerLetterPair + "and", letterPair.lowercased() + "&", "Spend", "Spend", .spend, [.token], [letterPair + "AND_API_KEY"], "ampersand", 0.07),
        item("zoommate", "ZoomMate", "Credits", "Credits", .credits, [.account, .cookie], ["ZOOMMATE_COOKIE"], "video", 0.19),
        item("x" + lowerLetterPair, "x" + letterPair, "Spend", "Spend", .spend, [.token], ["X" + letterPair + "_API_KEY"], "xmark", 0.32),
        item("notion", "Notion " + letterPair, "Rolling", "Monthly", .quota, [.account, .cookie], ["NOTION_COOKIE"], "n.square", 0.46),
        item("ibmbob", "IBM Bob", "Monthly Bobcoins", "Monthly Bobcoins", .credits, [.account, .token], ["IBM_BOB_API_KEY"], "b.circle", 0.58),
    ]

    static let byID = Dictionary(uniqueKeysWithValues: all.map { ($0.id, $0) })

    private static func item(
        _ id: String,
        _ name: String,
        _ primary: String,
        _ secondary: String,
        _ metric: ProviderMetricKind,
        _ sources: [ProviderSource],
        _ environmentKeys: [String],
        _ symbol: String,
        _ hue: Double,
        _ enabled: Bool = false
    ) -> ProviderDescriptor {
        ProviderDescriptor(
            id: ProviderID(rawValue: id),
            name: name,
            shortName: name,
            primaryLabel: primary,
            secondaryLabel: secondary,
            metricKind: metric,
            preferredSources: sources,
            environmentKeys: environmentKeys,
            defaultEndpoint: nil,
            symbol: symbol,
            hue: hue,
            defaultEnabled: enabled
        )
    }
}
